name: flutter lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  lint:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
      
      - name: flutter version
        run: flutter --version
      
      - name: flutter pub get
        run: flutter pub get
      
      - name: flutter analyze
        run: flutter analyze
