name: flutter lint

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main

jobs:
  lint:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
      
      - name: flutter version
        run: flutter --version
      
      - name: flutter pub get
        run: flutter pub get
      
      - name: flutter analyze
        run: flutter analyze
      
      - name: setup ruby
        if: ${{ failure() }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.3'
      
      - name: setup danger
        if: ${{ failure() }}
        run: |
          gem install bundler
          bundle install

      - uses: MeilCli/danger-action@v6
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}