name: Manual
on: 
    workflow_dispatch:
        inputs:
            name:
                type: string
                required: true
                description: please write your name
                default: Ken
jobs:
    run:
        runs-on: ubuntu-latest                
        steps:
        - name: greet
          run: echo "Hello, ${{ inputs.name }}!!"
        
        - name: description
          run: |
            echo "This workflow (${{ github.action }}) was triggered by ${{ github.actor }} on ${{ github.ref_name }}."

