name: Manual
on: 
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        description: please write your name
        default: Ken
      feeling:
        type: choice
        options:
          - happy
          - sad
          - hungry
        description: How are you feeling right now?

concurrency:
  group: ${{ github.workflow }}-${{github.ref}}
  cancel-in-progress: true

jobs:
  job-1:
    runs-on: ubuntu-latest      
    timeout-minutes: 3
    steps:
    - name: sleep if necessary
      if: ${{ inputs.name == 'Ken' }} 
      run: |
        echo sleep 4 minutes if inputs name == default value
        sleep 240
    
    - name: greet (read inputs)
      run: echo "Hello, ${{ inputs.name }}!! You are ${{ inputs.feeling }} now."
        
    - name: description
      run: echo "This workflow was triggered by ${{ github.actor }} on ${{ github.ref_name }}."

  job-2:
    runs-on: ubuntu-latest      
    steps:
    - name: 2 job (upload artifact which is file created in workfile)
      run: |
        sleep 10
        echo "This is job-2"
        echo "Hello! ${{ github.repository_owner }} in ${{ github.repository }}. $(TZ=Asia/Tokyo date +"%Y-%m-%d %H:%M:%S")" > sample.txt
    - uses: actions/upload-artifact@v4
      with:
        name: sample-artifact
        path: sample.txt
        retention-days: 3

  job-3:
    runs-on: ubuntu-latest
    steps:
    - name: 3 job (write and read GITHUB_OUTPUT, write outputs)
      id: third-job-1
      run: |
        echo "hoge=abc" >> "$GITHUB_OUTPUT" && sleep 5
    - name: overwrite hoge
      id: third-job-2
      env:
        TEST_RESULT: ${{ steps.third-job-1.outputs.hoge }}
      run: |
        echo "TEST_RESULT => ${TEST_RESULT}"
        echo "hoge=xyz" >> "$GITHUB_OUTPUT"
    outputs:
      test-data: ${{ steps.third-job-2.outputs.hoge }}

  job-4:
    runs-on: ubuntu-latest
    needs: [job-3]
    steps:
    - name: 4 job (read outputs)
      run: | 
        sleep 5
        echo github.event_name = ${{ github.event_name }}, runner.os = ${{ runner.os }}
        echo "JOB_3_RESULT => ${{ needs.job-3.outputs.test-data }}"

  job-5:
    runs-on: ubuntu-latest
    needs: [job-2]
    steps:
      - name: download artifact (= file created in workfile) in different job
        uses: actions/download-artifact@v4
        with:
          name: sample-artifact
          path: test-downloaded
      - run: cat test-downloaded/sample.txt
