name: Manual
on: 
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        description: please write your name
        default: Ken
concurrency:
  group: ${{ github.workflow }}-${{github.ref}}
  cancel-in-progress: true

jobs:
  job-1:
    runs-on: ubuntu-latest      
    timeout-minutes: 3
    steps:
    - name: sleep if necessary
      if: ${{ inputs.name == 'Ken' }} 
      run: |
        echo sleep 4 minutes if inputs name == default value
        sleep 240
    
    - name: greet
      run: echo "Hello, ${{ inputs.name }}!!"
        
    - name: description
      run: |
        echo "This workflow was triggered by ${{ github.actor }} on ${{ github.ref_name }}."

  job-2:
    runs-on: ubuntu-latest      
    steps:
    - name: second job
      run: |
        sleep 30
        echo "This is job-2"
        echo "github.repository = ${{ github.repository }}, github.repository_owner = ${{ github.repository_owner }}"

  job-3:
    runs-on: ubuntu-latest
    steps:
    - name: third job (echo GITHUB_OUTPUT)
      id: third-job-id
      run: |
        echo "hoge=abc" >> "${GITHUB_OUTPUT}"
        sleep 30 && echo "This is job-3 (github.repository_owner = ${{ github.repository_owner }})"
    - env:
        TEST_RESULT: ${{ steps.third-job-id.outputs.hoge }}
      run: echo "${TEST_RESULT}"

  job-4:
    runs-on: ubuntu-latest
    needs: [job-2]
    steps:
    - name: fourth job
      run: | 
        echo
        sleep 30 && echo "This is job-4 (github.repository_owner = ${{ steps }})"